### PR TITLE
purrr::when changes

### PR DESCRIPTION
**Pull request by hfuchs5**
What changes are involved in this pull request? Is there a GitHub issue corresponding to this pull request? If so, please provide link.

Changing purrr::when to loops. In order to use switch(), the output needs to be the same class as the input, so loops are more efficient here.

Checklist
- [ ] Make sure all updates from master branch are pulled to branch issuing pull request
- [ ] Confirm package dependencies are installed by running `renv::install()`
- [ ] For bug corrections, check that unit test was added
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website
- [ ] Code coverage is suitable for any new functions/features. Review coverage with `covr::report()`. Before you run, begin in a fresh R session without any packages loaded and set `Sys.setenv(NOT_CRAN="true")`.
- [ ] R CMD Check runs without errors, warnings, and notes
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation
- [ ] Document changes from this pull request in `NEWS.md` file
- [ ] Increment the version number using `usethis::use_version(which = "dev")`
- [ ] Approve and merge pull request

### CODE REVIEW

**Review by michaelcurry1123 — COMMENTED** [review]
in pull data synapse line 114 this code will throw and error if the version numbers match each other. the setdiff will return a empty vector and you can't test a logical condition against it.   `setdiff(version, unique(synapse_tables$version)) > 0` 
something like this might work:
`length(setdiff(version, unique(synapse_tables$version))) > 0`

**Review by michaelcurry1123 — COMMENTED** [review]
@hfuchs5 I would possibly make a test for fetch_samples to test the change with the sample types  just to make sure they are coded correctly.  @jalavery The cohort input doesn't do anything in fetch_samples. Do we need it for anything?

**Comment by hfuchs5** [comment]
@michaelcurry1123 I was having trouble with running tests because regardless of using set_synapse_login() it keeps skipping all the tests because of .is_connected_to_genie(). Jessica said it might be a cloud mapping problem.

**Comment by jalavery** [comment]
Thank you both for your work on this PR! Please add both of your names to the author list for this function.

@hfuchs5 To run tests locally, open the GENIE package R project and edit your R environment via `usethis::edit_r_environ()` to include your synapse credentials. It's a different R environment file than when you are outside of the GENIE package. Once your synapse credentials are in the package environ file, restart your R session and the tests should run. Let me know if they don't and we can troubleshoot.

@michaelcurry1123 If the cohort input parameter isn't being used we can remove. One less place to update documentation when a new cohort is added.

**Review by jalavery — APPROVED** [review]
Thanks Hannah & Mike!

**Pull request merged**
