### PR TITLE
Update unique ngs error

### PR DESCRIPTION
**Pull request by karissawhiting**
**What changes are involved in this pull request? Is there a GitHub issue corresponding to this pull request? If so, please provide link.**

Addresses #57.  Refactored `select_unique_ngs()` and improved errors/warnings. 

@jalavery -  error message still displays all the IDs for which each warning applies but in nicer formatting. Should we remove these ID and just keep the summary counts in the message? Maybe they are not needed.

**Checklist**
- [x] Make sure all updates from master branch are pulled to branch issuing pull request
- [x] Confirm package dependencies are installed by running `renv::install()`
- [ ] For bug corrections, check that unit test was added
- [x] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website
- [ ] Code coverage is suitable for any new functions/features. Review coverage with `covr::report()`. Before you run, begin in a fresh R session without any packages loaded and set `Sys.setenv(NOT_CRAN="true")`.
- [x] R CMD Check runs without errors, warnings, and notes
- [x] `usethis::use_spell_check()` runs with no spelling errors in documentation
- [x] Document changes from this pull request in `NEWS.md` file
- [x] Increment the version number using `usethis::use_version(which = "dev")`
- [x] Approve and merge pull request

### CODE REVIEW

**Comment by michaelcurry1123** [comment]
@karissawhiting  @jalavery  should we in this branch also address the `.data` issues we have ? or approve this pr, merge it into main and then update the branch to update the select tidiers? I was thinking there might be a merge conflict down the line? if not please ignore this message

**Comment by jalavery** [comment]
@karissawhiting the refactored code looks beautiful! ✨ 

the error messaging is definitely clearer. the only comment I had while reviewing is that I am worried that using the language 'duplicated' makes it sound like the same NGS report recorded >1x as opposed to multiple CPT reports per pt. I pushed a suggested tweak to the wording - feedback welcome!

**Comment by karissawhiting** [comment]
Looks great! I think it could be merged

**Comment by jalavery** [comment]
Great! 🎉 Thanks for taking a look. Will finish the PR checklist & merge in today

In looking at this and thinking about the messaging I realized that `select_unique_ngs()` is based on selecting a unique NGS per patient (among the diagnoses subset on `cohort_ngs`), which is almost always going to be the structure of the diagnosis dataset returned from `create_analytic_cohort()`, so this is perfect for now. It is technically possible for someone to pull multiple cancer diagnoses per patient, and those cancer diagnoses would have different NGS reports and we wouldn't want to restrict to 1 NGS report across all dx, so I am going to open an issue to remind us that a future enhancement could be updating `select_unique_ngs()` to be unique at the diagnosis rather than at the patient level. Not sure how difficult this is to implement, but we can discuss once we're past this release and paper revision!

**Review by jalavery — APPROVED** [review]

**Pull request merged**
